version: '2'
services:
 db:
  image: mongo:3.4
 backend:
  image: node:8.1
  volumes: 
    - ./backend:/backend
  environment:
    NODE_ENV: development
  ports: 
    - 3003:3003
  command: bash -c "cd /backend && npm i -g && SENDGRID_API_KEY=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 npm start"
  depends_on:
      - "db"
#  frontend: 
#   image: frontend-grifoo
#   build: ./frontend/.
#   links: 
#     - "backend:backend"
#   environment:
#     NODE_ENV: development
#   ports:
#     - 4200:4200
#   depends_on:
#       - "backend"