version: '2'
networks: 
  web:
  queue:
  db:
services:
 db:
  image: mongo:3.4
  volumes: 
    - /data/db:/data/db
  networks: 
    - db
  ports: 
    - 27017:27017
  env_file: 
   - 'enviroments.env'
 pedidos:
  image: node:8.1
  volumes: 
   - ./pedidos:/pedidos
  ports: 
   - 3003:3003
  command: bash -c "cd /pedidos && npm i && npm start"
  depends_on:
   - "db"
   - "queue"
  networks: 
   - web
   - db
   - queue
  env_file: 
   - 'enviroments.env'
 parceiros:
  image: node:8.1
  volumes: 
   - ./pedidos:/pedidos
  ports: 
   - 3004:3003
  command: bash -c "cd /parceiros && npm i && npm start"
  depends_on:
   - "db"
   - "queue"
  networks: 
   - web
   - db
   - queue
  env_file: 
   - 'enviroments.env'
 frontend:
  image: nginx:1.13
  volumes: 
    - ./frontend/dist/:/usr/share/nginx/html
    - ./nginx/default.conf:/etc/nginx/confi.d/default.conf
  ports:  
    - 80:80
  depends_on:
    - "pedidos"
    - "db"
  networks: 
    - web
  env_file: 
   - 'enviroments.env'
 queue:
  image: redis
  networks: 
   - queue
  ports: 
    - 6379:6379
 worker:
  image: node:8.1
  volumes: 
    - ./worker:/worker
  command: bash -c "cd /worker && npm i -g --no-optional && npm start"
  depends_on: 
    - "db"
    - "queue"
  networks: 
    - db
    - queue
    - web
  links: 
    - pedidos:pedidos
  env_file: 
   - 'enviroments.env'