version: '2'
networks: 
  web:
  queue:
  db:
services:
 db:
  image: mongo:3.4
  volumes: 
    - /data/db:/data/db
  networks: 
    - db
 backend:
  image: node:8.1
  volumes: 
   - ./backend:/backend
  ports: 
   - 3003:3003
  command: bash -c "cd /backend && npm i -g sendgrid && npm i && npm start"
  depends_on:
   - "db"
   - "queue"
  networks: 
   - web
   - db
   - queue
 frontend:
  image: nginx:1.13
  volumes: 
    - ./frontend/dist/:/usr/share/nginx/html
    - ./nginx/default.conf:/etc/nginx/confi.d/default.conf
  ports:  
    - 80:80
  depends_on:
    - "backend"
    - "db"
  networks: 
    - web
 queue:
  image: redis
  networks: 
   - queue
  ports: 
    - 6379:6379
 worker:
  image: node:8.1
  volumes: 
    - ./worker:/worker
  command: bash -c "cd /worker && npm i -g --no-optional && npm start"
  depends_on: 
    - "db"
    - "queue"
  networks: 
    - db
    - queue
   
 #  frontend: 
#   image: node:8.1
#   volumes: 
#     - ./frontend:/frontend
#   command: bash -c "cd /frontend && npm i -g && npm start"
#   links: 
#     - "backend:backend"
#   ports:
#     - 4200:4200
#   depends_on:
#       - "backend"
  # frontend: 
  #   image: frontend-grifoo
  #   build: ./frontend/.
  #   links: 
  #     - "backend:backend"
  #   ports:
  #     - 4200:4200
  #   depends_on:
  #       - "backend"