version: '2'
services:
 db:
  image: mongo:3.4
 backend:
  image: node:8.1
  volumes: 
    - ./backend:/backend
  ports: 
    - 3003:3003
  command: bash -c "cd /backend && npm i -g && SENDGRID_API_KEY='' npm start"
  depends_on:
      - "db"
 frontend: 
  image: frontend-grifoo
  build: ./frontend/.
  links: 
    - "backend:backend"
  ports:
    - 4200:4200
  depends_on:
      - "backend"