version: '2'
networks: 
  private:
services:
 db:
  image: mongo:3.4
  volumes: 
    - /data/db:/data/db
  networks: 
    - private
  ports: 
    - 27017:27017
  env_file: 
   - 'enviroments.env'
 pedidos:
  build: ./pedidos
  ports: 
  - 3003:3003
  volumes: 
   - ./pedidos:/app
  depends_on:
   - "db"
   - "queue"
  networks: 
   - private
  env_file: 
   - 'enviroments.env'
  links: 
   - queue:queue
 parceiros:
  build: ./parceiros 
  ports: 
   - 3004:3004
  depends_on:
   - "db"
   - "queue"
  networks: 
   - private
  env_file: 
   - 'enviroments.env'
 iam:
  build: ./parceiros 
  ports: 
   - 3005:3005
  depends_on:
   - "db"
   - "queue"
  networks: 
   - private
  env_file: 
   - 'enviroments.env'
 frontend:
  image: nginx:1.13
  volumes: 
    - ./frontend/dist/:/usr/share/nginx/html
    - ./nginx/default.conf:/etc/nginx/confi.d/default.conf
  ports:  
    - 80:80
  depends_on:
    - "pedidos"
    - "parceiros"
    - "db"
  networks: 
    - private
  env_file: 
   - 'enviroments.env'
 queue:
  image: redis
  networks: 
   - private
  ports: 
    - 6379:6379
 worker:
  build: ./worker
  volumes: 
    - ./worker:/app
  depends_on: 
    - "db"
    - "queue"
  networks: 
    - private
  links: 
    - pedidos:pedidos
    - parceiros:parceiros
  env_file: 
   - 'enviroments.env'