swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8081'
basePath: /
tags:
  - name: cliente-controller
    description: Operações para gerenciamento de clientes
paths:
  /clientes:
    get:
      tags:
        - cliente-controller
      summary: Listar todos os clientes
      operationId: buscarTodosclientesUsingGET
      produces:
        - '*/*'
        - application/json
      responses:
        '200':
          description: Dados recuperados com sucesso
          schema:
            type: array
            items:
              $ref: '#/definitions/Cliente'
        '204':
          description: Não existem dados para serem recuperados
          schema:
            type: array
            items:
              $ref: '#/definitions/Cliente'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - cliente-controller
      summary: Salva um cliente
      operationId: saveUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
        - application/json
      parameters:
        - in: body
          name: cliente
          description: cliente
          required: true
          schema:
            $ref: '#/definitions/Cliente'
      responses:
        '200':
          description: OK
        '201':
          description: Operação realizada com sucesso
        '400':
          description: Dados invalidos
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/clientes/{clienteId}':
    get:
      tags:
        - cliente-controller
      summary: Recuera um cliente por id
      operationId: buscarClientePorIdUsingGET
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
      responses:
        '200':
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/Cliente'
        '400':
          description: Dados invalidos
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Recurso não encontrado
  '/clientes/{id}':
    put:
      tags:
        - cliente-controller
      summary: Atualiza informações do cliente por id
      operationId: autalizarClienteUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: query
          description: id
          required: true
          type: string
        - in: body
          name: cliente
          description: cliente
          required: true
          schema:
            $ref: '#/definitions/Cliente'
      responses:
        '200':
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/Cliente'
        '201':
          description: Created
        '400':
          description: Dados invalidos
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Recurso não encontrado
    delete:
      tags:
        - cliente-controller
      summary: Remove um cliente por id
      operationId: deletarClienteUsingDELETE
      produces:
        - application/json
      parameters:
        - name: id
          in: query
          description: id
          required: true
          type: string
        - in: body
          name: cliente
          description: cliente
          required: true
          schema:
            $ref: '#/definitions/Cliente'
      responses:
        '200':
          description: Operação realizada com sucesso
        '204':
          description: No Content
        '400':
          description: Dados invalidos
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Recurso não encontrado
definitions:
  Cliente:
    type: object
    properties:
      email:
        type: string
      id:
        type: string
      nome:
        type: string
      telefone:
        type: string
    title: Cliente
